import type { Metadata } from "next";
import "./globals.css";
import { ColourContextProvider } from '@/context/ColourContext';
import Canvas from "@/components/Canvas";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <ColourContextProvider>
          <Canvas />
          {children}
        </ColourContextProvider>
      </body>
    </html>
  );
}
